### ISSUE TITLE
Automate release

### ISSUE THREAD

**Issue by arvgord** [GoogleCloudPlatform/qupath-chcapi-extension#12]

**Comment by poojavenkatram** [comment]
One pending item here is to update the wiki - we can close this out once that is done.

**Comment by pavertomato** [comment]
> One pending item here is to update the wiki - we can close this out once that is done.

Wiki is not available for editing, could you please enable it?

**Comment by arvgord** [comment]
This may help - https://help.github.com/en/articles/changing-access-permissions-for-wikis

**Comment by poojavenkatram** [comment]
Yeah my qualm with that is it opens it up to everyone - like anyone in the public can go and update it. I don't think that is a good idea - just trying to see where is the best place to put this.

**Comment by arvgord** [comment]
We still can't access the wiki page...

**Comment by poojavenkatram** [comment]
Sorry I thought this was done - I have changed the access, please let me know if you still have issues accessing the Wiki. Thanks.

**Comment by poojavenkatram** [comment]
Followed the Wiki and was able to publish a new release - thank you so much for adding the steps :)

**Comment by poojavenkatram** [comment]
The build is failing when I try to create a release: https://pantheon.corp.google.com/cloud-build/builds/e44be690-caa6-4c06-a723-8d9de4c46029?authuser=1&project=gcp-healthcare-oss-test

**Comment by pavertomato** [comment]
for weasis and qupath, seems like github robot don't have permissions, we had same problem with wsi https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/issues/6#issuecomment-510222047

for weasis - versions of dependency and application was glued together
PR to fix this https://github.com/GoogleCloudPlatform/weasis-chcapi-extension/pull/31
