### ISSUE TITLE
ListProjects is limited to the first 1k projects

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/qupath-chcapi-extension#2]
In the project selector dialog, only the first 1k projects the user has access to are shown. The selector should either download all pages (might be slow) or the search query should be sent to the resourcemanager API.

**Comment by arvgord** [comment]
Fixed the projects page to correctly handle > 1k projects.

**Comment by dzelemba** [comment]
Can you open up a new pull request to merge the changes in instead of combining with the other one? It'll be easier to review and we can get things in faster if we break up fixes like this into their own PRs.

**Comment by arvgord** [comment]
Maybe in the current pull request we will use it without changes? Because trying to separate this into multiple requests may cause conflicts. Next changes we will upload separately. More detailed conversation: https://github.com/GoogleCloudPlatform/qupath-chcapi-extension/pull/1

**Comment by arvgord** [comment]
Can we close this issue?
