### ISSUE TITLE
Upgrade Jackson Dependency

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/qupath-chcapi-extension#21]
Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.10 or later.

This came from a GitHub security alert.

**Comment by arvgord** [comment]
Done

**Comment by dzelemba** [comment]
New security alert: Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.10.1 or later.

**Comment by arvgord** [comment]
Updated jackson-databind to 2.9.10.1

**Comment by poojavenkatram** [comment]
Pull Request: #27
