### ISSUE TITLE
QuPath Build is timing out when creating JARs for the release

### ISSUE THREAD

**Issue by poojavenkatram** [GoogleCloudPlatform/qupath-chcapi-extension#24]
https://pantheon.corp.google.com/cloud-build/builds/d22d4f2e-3be4-4641-806c-1c7b996c7a3c?project=gcp-healthcare-oss-test

https://pantheon.corp.google.com/cloud-build/builds/b8911104-76e8-4e55-8080-0b5774975ba1?project=gcp-healthcare-oss-test

**Comment by pavertomato** [comment]
seems like it was temporary cloud build's issue
i've triggered build for same branch and it finished well https://console.cloud.google.com/cloud-build/builds/880fadce-b932-4d41-b1bf-62f1969274d0?project=gcp-healthcare-oss-test

**Comment by pavertomato** [comment]
build usually takes  ≈4mins, we may set timeout of build to 20 minutes,  but if cloud build stuck for more than 10min it may stuck for 20 as well?

**Comment by poojavenkatram** [comment]
Yup this worked today - looks like Cloud Build was just slow yesterday when I tried this.
