### ISSUE TITLE
Synch to GCP

### ISSUE THREAD

**Issue by NickOGrady** [GoogleCloudPlatform/qupath-chcapi-extension#28]
I am able to connect to my GCP project, dataset and data store.  When synching, QuPath loads the single DCM image I have in my data store - I can see some text where a file name would be, but the image itself does not load.  

As a reverse test, I imported the same image locally, and QuPath is able to display the image.  When I go to synch with the local image loaded, I get the following error message:
java.lang.NoClassDefFoundError: Could not initialize class
com.quantumsoft.qupathcloud.converter.dicomizer.wsi2dcmLibrary

Any ideas on how to display the images from my data store?  Thank you!

**Comment by red1408** [comment]
As for why it doesn't work when uploaded by other means, are sure that the image is a [whole slide image](http://dicom.nema.org/Dicom/DICOMWSI/)?

From email context I assume that the local image is a .dcm file? Qupath chcapi extension does not expect a local .dcm , we expect any file formats supported by [OpenSlide](https://openslide.org/).

Also, your first email shows that you had 2 versions of qupath chc api extension installed at the same time.

> INFO: Added extension: /Users/nogrady1/QuPath/extensions/qupath-chcapi-extension-2.0.3.jar
> INFO: Added extension: /Users/nogrady1/QuPath/extensions/qupath-cloud-1.0-jar-with-dependencies.jar

This is likely to cause unpredictable issues. Please remove the older one.

**Comment by dzelemba** [comment]
Yes using radiology images won't work with this viewer unfortunately. QuPath will automatically DICOMize any WSI images using OpenSlide and upload them to the Healthcare API DICOM Store. If you want to convert yourself and upload to the DICOM store, we also have this converter: https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter.

For the NoClassDefFound error, could you describe which version of the plugin you're using and which version of QuPath you're using? Also which operating system and version. 

Finally, I should mention that OHIF also supports viewing of DICOM WSIs and is also integrated with the Healthcare API: https://docs.ohif.org/connecting-to-image-archives/google-cloud-healthcare.html

**Comment by NickOGrady** [comment]
Hi all,
Thank you both for your responses and help.  I have since deleted any my multiple copies of qupath versions.  I am using qupath-0.2.0-m2, plugin v2.0.5, and mac OS 10.13.6 (high sierra). 

I suspect you were right about me not testing a correct image format.  Our actual pathology images are from an Aperio scanner, so .svs files.  When I load a local .svs file, qupath is able to correctly synch to the datastore. 
However, what I want to do is load images from say a google bucket, to the datastore, and then into qupath.  Am I correct in thinking that the datastore requires DICOMized images? 
https://cloud.google.com/healthcare/docs/how-tos/dicom-import-export
All of the images in our buckets are .svs files.  If so, I will try this converter out that you recommended:
https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter
As an aside- `brew install wsi2dcm.rb` however doesn't work since there doesn't seem to be an active formula with that name.  I will work on installing through other means.

Thanks!

**Comment by pavertomato** [comment]
>I suspect you were right about me not testing a correct image format. Our actual pathology images are from an Aperio scanner, so .svs files. When I load a local .svs file, qupath is able to correctly synch to the datastore.

qupath actually use https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter so if you synced your svs file it means what qupath generated dicom files and uploaded them

> However, what I want to do is load images from say a google bucket, to the datastore, and then into qupath. Am I correct in thinking that the datastore requires DICOMized images?

if your images is dicom you may just import them into datastore https://cloud.google.com/healthcare/docs/how-tos/dicom-import-export
if your images is svs you may dicomize them by qupath(and upload at same time) or you may use wsi2dcm

>to the datastore, and then into qupath.

qupath using datastore so all you need is just select the one with your upload

>As an aside- brew install wsi2dcm.rb however doesn't work since there doesn't seem to be an active formula with that name. I will work on installing through other means.

brew file is unique for each release so it's generated each time and master branch contains only template for it, you should use brew file from release https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/releases/tag/v1.0.2
``` brew install https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/releases/download/v1.0.2/wsi2dcm.rb```

if you'll have any questions regarding wsi2dcm please create new issue here https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/issues

**Comment by NickOGrady** [comment]
Hi all- Thanks for the brew file tip.  I have the wsi2dcm converter installed and running.  For now I think I have this extension working fine, I think any other issues I have will be for the wsi2dcm converter, which I'll start a thread over there if needed.  Thanks for the help and this very useful extension!

**Comment by dzelemba** [comment]
Glad to hear all is working!
