### ISSUE TITLE
metadata read error

### ISSUE THREAD

**Issue by pavertomato** [GoogleCloudPlatform/qupath-chcapi-extension#3]
qupath fails to read metada for DCM generated from http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1.svs 
and http://openslide.cs.cmu.edu/download/openslide-testdata/Generic-TIFF/CMU-1.tiff

but  files in {project}/metadata/ is generated and seems to be ok - [2.25.102935203982899004173368452425451853510.mtd.txt](https://github.com/GoogleCloudPlatform/qupath-chcapi-extension/files/3070646/2.25.102935203982899004173368452425451853510.mtd.txt)
for http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/JP2K-33003-1.svs everything is ok

**Comment by red1408** [comment]
There is no (0028,0008) Number of Frames on last level.
