### ISSUE TITLE
HandShake exception trying to log into account

### ISSUE THREAD

**Issue by sdvillal** [GoogleCloudPlatform/qupath-chcapi-extension#33]
Using qupath 0.2.0.m5 and the extension version 2.0.5 in macos, I'm trying to login to my account. After clicking "cloud", a browser window is opened asking for authorisation for the app. Until here everything normal. Now, to login into my account I actually need to go into a "private" browser window (otherwise I can only login using my primary identity, that is not allowed by my company policies). So I copy and paste the url in this private window, I get asked to grant permission to qupath which I do and, at the end of the process, I get an error like this:

```
com.quantumsoft.qupathcloud.exception.QuPathCloudException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```

Any subsequent attempt to click the button results in a NullPointerException. These are full logs:

```
INFO: Project set to Project: test-qupath-project-project
INFO: Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
INFO: jetty-6.1.x
INFO: Started SocketConnector@localhost:58717
INFO: Stopped SocketConnector@localhost:58717
ERROR: QuPath exception
    at com.quantumsoft.qupathcloud.oauth20.OAuth20.getCredential(OAuth20.java:83)
    at com.quantumsoft.qupathcloud.dao.CloudDaoImpl.createRequestForObjectList(CloudDaoImpl.java:352)
    at com.quantumsoft.qupathcloud.dao.CloudDaoImpl.getProjects(CloudDaoImpl.java:124)
    at com.quantumsoft.qupathcloud.gui.windows.CloudWindow.lambda$authorizationPage$4(CloudWindow.java:184)
    at java.base/java.lang.Thread.run(Unknown Source)
INFO: jetty-6.1.x
INFO: Started SocketConnector@localhost:58787
INFO: Stopped SocketConnector@localhost:58787
ERROR: QuPath exception
    at com.quantumsoft.qupathcloud.oauth20.OAuth20.getCredential(OAuth20.java:83)
    at com.quantumsoft.qupathcloud.dao.CloudDaoImpl.createRequestForObjectList(CloudDaoImpl.java:352)
    at com.quantumsoft.qupathcloud.dao.CloudDaoImpl.getProjects(CloudDaoImpl.java:124)
    at com.quantumsoft.qupathcloud.gui.windows.CloudWindow.lambda$authorizationPage$4(CloudWindow.java:184)
    at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by arvgord** [comment]
I'll try to reproduce this issue. Could you please give a bit more information?
- Do you use proxy in a browser?
- Does your system have custom root certificates(eg. company cert for corporate net)?

**Comment by sdvillal** [comment]
Although I need to be in my corporate network to login to GCP, I can then just work in non-corporate network and so I do not think there is any proxy involved. About SSL certificates, we definitely have custom root certificates but again I do not know how these apply to be honest.

**Comment by arvgord** [comment]
Could you launch QuPath in the terminal as described in the [README](https://github.com/GoogleCloudPlatform/qupath-chcapi-extension#note)(Note point)?

**Comment by arvgord** [comment]
I've investigated this issue and I figured out that AdoptOpenJDK hasn't some cipher suites for TLSv1.2(QuPath uses built-in AdoptOpenJDK by default). To solve this issue you can use OpenJDK or Amazon Corretto instead of built-in AdoptOpenJDK, as I described above. Have you tried to run QuPath with system java?

**Comment by sdvillal** [comment]
Your diagnosis is correct (see https://github.com/qupath/qupath/issues/436). I will close this now, thanks @arvgord!
