### ISSUE TITLE
Adapt to QuPath version 0.2.0m10

### ISSUE THREAD

**Issue by sdvillal** [GoogleCloudPlatform/qupath-chcapi-extension#35]
[QuPath 0.2.0m10](https://github.com/qupath/qupath/releases/tag/v0.2.0-m10) comes with a large refactoring effort that has broken the extension.

xref: https://github.com/qupath/qupath/issues/436
xref: https://github.com/qupath/qupath/issues/454

**Comment by poojavenkatram** [comment]
Hi Santi, 
Thanks for filing this - this is now resolved and a new JAR has been released which is compatible with the new QuPath version.

**Comment by sdvillal** [comment]
Thank you, it works like a charm!

**Comment by poojavenkatram** [comment]
That's great - thanks for reporting the issue.
